language: node_js
node_js:
- 6.2.2
install:
- npm install
script:
- node app.js & npm test
services:
- memcached
cache:
  directories:
  - node_modules
notifications:
  email:
  - deep.dhillon@socrata.com
  - lane.aasen@socrata.com
  - tosh.meston@gmail.com
  - chris.metcalf@socrata.com
